import {
  categoryConfigSchema,
  type CategoryConfig,
  type Requirement,
} from "@/lib/contracts";

type MandatoryRequirement = Omit<Requirement, "kind" | "weight" | "source" | "needsConfirmation">;
type PreferredRequirement = Pick<Requirement, "id" | "criterionKey" | "label" | "unit" | "weight">;

const mandatory = (requirement: MandatoryRequirement): Requirement => ({
  ...requirement,
  kind: "mandatory",
  weight: 0,
  source: "category_default",
  needsConfirmation: false,
});

const preferred = (requirement: PreferredRequirement): Requirement => ({
  ...requirement,
  kind: "preferred",
  operator: null,
  target: null,
  source: "category_default",
  needsConfirmation: false,
});

const rawCategoryConfigs: CategoryConfig[] = [
  {
    category: "laptop",
    label: "Laptop",
    examplePrompt:
      "I need a laptop under S$1,800 with at least 16 GB RAM and 512 GB storage for development and travel.",
    criteria: [
      {
        key: "price_sgd",
        label: "Price",
        valueType: "number",
        unit: "SGD",
        supportedRequirementKinds: ["mandatory", "preferred"],
        allowedMandatoryOperators: ["lte"],
        scoringMode: "lower_is_better",
        defaultWeight: 30,
      },
      {
        key: "ram_gb",
        label: "RAM",
        valueType: "number",
        unit: "GB",
        supportedRequirementKinds: ["mandatory", "preferred"],
        allowedMandatoryOperators: ["gte"],
        scoringMode: "higher_is_better",
        defaultWeight: 20,
      },
      {
        key: "storage_gb",
        label: "Storage",
        valueType: "number",
        unit: "GB",
        supportedRequirementKinds: ["mandatory"],
        allowedMandatoryOperators: ["gte"],
        scoringMode: "higher_is_better",
        defaultWeight: 0,
      },
      {
        key: "battery_life_h",
        label: "Battery life",
        valueType: "number",
        unit: "h",
        supportedRequirementKinds: ["preferred"],
        allowedMandatoryOperators: [],
        scoringMode: "higher_is_better",
        defaultWeight: 20,
      },
      {
        key: "weight_kg",
        label: "Weight",
        valueType: "number",
        unit: "kg",
        supportedRequirementKinds: ["preferred"],
        allowedMandatoryOperators: [],
        scoringMode: "lower_is_better",
        defaultWeight: 15,
      },
      {
        key: "geekbench_6_multicore",
        label: "Geekbench 6 multicore performance",
        valueType: "number",
        unit: "Geekbench 6 multicore points",
        supportedRequirementKinds: ["preferred"],
        allowedMandatoryOperators: [],
        scoringMode: "higher_is_better",
        defaultWeight: 15,
      },
    ],
    defaultRequirements: [
      mandatory({
        id: "laptop-max-price",
        criterionKey: "price_sgd",
        label: "Maximum price",
        operator: "lte",
        target: 1800,
        unit: "SGD",
      }),
      mandatory({
        id: "laptop-min-ram",
        criterionKey: "ram_gb",
        label: "Minimum RAM",
        operator: "gte",
        target: 16,
        unit: "GB",
      }),
      mandatory({
        id: "laptop-min-storage",
        criterionKey: "storage_gb",
        label: "Minimum storage",
        operator: "gte",
        target: 512,
        unit: "GB",
      }),
      preferred({ id: "laptop-prefer-price", criterionKey: "price_sgd", label: "Prefer a lower price", unit: "SGD", weight: 30 }),
      preferred({ id: "laptop-prefer-ram", criterionKey: "ram_gb", label: "Prefer more RAM", unit: "GB", weight: 20 }),
      preferred({ id: "laptop-prefer-battery", criterionKey: "battery_life_h", label: "Prefer longer battery life", unit: "h", weight: 20 }),
      preferred({ id: "laptop-prefer-weight", criterionKey: "weight_kg", label: "Prefer lower weight", unit: "kg", weight: 15 }),
      preferred({
        id: "laptop-prefer-cpu",
        criterionKey: "geekbench_6_multicore",
        label: "Prefer higher CPU performance",
        unit: "Geekbench 6 multicore points",
        weight: 15,
      }),
    ],
  },
  {
    category: "air_purifier",
    label: "Air purifier",
    examplePrompt:
      "I need an air purifier under S$600 for a 40 m² room, with CADR of at least 300 m3/h and sensible running costs.",
    criteria: [
      {
        key: "price_sgd",
        label: "Price",
        valueType: "number",
        unit: "SGD",
        supportedRequirementKinds: ["mandatory", "preferred"],
        allowedMandatoryOperators: ["lte"],
        scoringMode: "lower_is_better",
        defaultWeight: 25,
      },
      {
        key: "cadr_m3h",
        label: "Clean air delivery rate",
        valueType: "number",
        unit: "m3/h",
        supportedRequirementKinds: ["mandatory", "preferred"],
        allowedMandatoryOperators: ["gte"],
        scoringMode: "higher_is_better",
        defaultWeight: 25,
      },
      {
        key: "coverage_m2",
        label: "Room coverage",
        valueType: "number",
        unit: "m2",
        supportedRequirementKinds: ["mandatory", "preferred"],
        allowedMandatoryOperators: ["gte"],
        scoringMode: "higher_is_better",
        defaultWeight: 20,
      },
      {
        key: "noise_dba",
        label: "Noise",
        valueType: "number",
        unit: "dB(A)",
        supportedRequirementKinds: ["preferred"],
        allowedMandatoryOperators: [],
        scoringMode: "lower_is_better",
        defaultWeight: 15,
      },
      {
        key: "annual_filter_cost_sgd",
        label: "Annual filter cost",
        valueType: "number",
        unit: "SGD/year",
        supportedRequirementKinds: ["preferred"],
        allowedMandatoryOperators: [],
        scoringMode: "lower_is_better",
        defaultWeight: 10,
      },
      {
        key: "power_consumption_w",
        label: "Power consumption",
        valueType: "number",
        unit: "W",
        supportedRequirementKinds: ["preferred"],
        allowedMandatoryOperators: [],
        scoringMode: "lower_is_better",
        defaultWeight: 5,
      },
    ],
    defaultRequirements: [
      mandatory({ id: "air-max-price", criterionKey: "price_sgd", label: "Maximum price", operator: "lte", target: 600, unit: "SGD" }),
      mandatory({ id: "air-min-cadr", criterionKey: "cadr_m3h", label: "Minimum CADR", operator: "gte", target: 300, unit: "m3/h" }),
      mandatory({ id: "air-min-coverage", criterionKey: "coverage_m2", label: "Minimum room coverage", operator: "gte", target: 40, unit: "m2" }),
      preferred({ id: "air-prefer-price", criterionKey: "price_sgd", label: "Prefer a lower price", unit: "SGD", weight: 25 }),
      preferred({ id: "air-prefer-cadr", criterionKey: "cadr_m3h", label: "Prefer higher CADR", unit: "m3/h", weight: 25 }),
      preferred({ id: "air-prefer-coverage", criterionKey: "coverage_m2", label: "Prefer greater room coverage", unit: "m2", weight: 20 }),
      preferred({ id: "air-prefer-noise", criterionKey: "noise_dba", label: "Prefer lower noise", unit: "dB(A)", weight: 15 }),
      preferred({ id: "air-prefer-filter-cost", criterionKey: "annual_filter_cost_sgd", label: "Prefer lower annual filter cost", unit: "SGD/year", weight: 10 }),
      preferred({ id: "air-prefer-power", criterionKey: "power_consumption_w", label: "Prefer lower power consumption", unit: "W", weight: 5 }),
    ],
  },
  {
    category: "lab_oven",
    label: "Lab oven",
    examplePrompt:
      "I need a 230 V single-phase lab oven under S$8,000 that reaches at least 250 °C and has at least 50 L chamber volume.",
    criteria: [
      {
        key: "price_sgd",
        label: "Price",
        valueType: "number",
        unit: "SGD",
        supportedRequirementKinds: ["mandatory", "preferred"],
        allowedMandatoryOperators: ["lte"],
        scoringMode: "lower_is_better",
        defaultWeight: 25,
      },
      {
        key: "max_temperature_c",
        label: "Maximum temperature",
        valueType: "number",
        unit: "°C",
        supportedRequirementKinds: ["mandatory", "preferred"],
        allowedMandatoryOperators: ["gte"],
        scoringMode: "higher_is_better",
        defaultWeight: 25,
      },
      {
        key: "chamber_volume_l",
        label: "Chamber volume",
        valueType: "number",
        unit: "L",
        supportedRequirementKinds: ["mandatory", "preferred"],
        allowedMandatoryOperators: ["gte"],
        scoringMode: "higher_is_better",
        defaultWeight: 20,
      },
      {
        key: "electrical_profile",
        label: "Electrical compatibility",
        valueType: "string",
        unit: "electrical_profile",
        supportedRequirementKinds: ["mandatory"],
        allowedMandatoryOperators: ["eq"],
        scoringMode: "threshold",
        defaultWeight: 0,
      },
      {
        key: "temperature_uniformity_c",
        label: "Temperature uniformity",
        valueType: "number",
        unit: "±°C",
        supportedRequirementKinds: ["preferred"],
        allowedMandatoryOperators: [],
        scoringMode: "lower_is_better",
        defaultWeight: 20,
      },
      {
        key: "power_consumption_w",
        label: "Power consumption",
        valueType: "number",
        unit: "W",
        supportedRequirementKinds: ["preferred"],
        allowedMandatoryOperators: [],
        scoringMode: "lower_is_better",
        defaultWeight: 10,
      },
    ],
    defaultRequirements: [
      mandatory({ id: "oven-max-price", criterionKey: "price_sgd", label: "Maximum price", operator: "lte", target: 8000, unit: "SGD" }),
      mandatory({ id: "oven-min-temperature", criterionKey: "max_temperature_c", label: "Minimum maximum temperature", operator: "gte", target: 250, unit: "°C" }),
      mandatory({ id: "oven-min-volume", criterionKey: "chamber_volume_l", label: "Minimum chamber volume", operator: "gte", target: 50, unit: "L" }),
      mandatory({
        id: "oven-electrical-profile",
        criterionKey: "electrical_profile",
        label: "Electrical compatibility",
        operator: "eq",
        target: "230V_50HZ_SINGLE_PHASE",
        unit: "electrical_profile",
      }),
      preferred({ id: "oven-prefer-price", criterionKey: "price_sgd", label: "Prefer a lower price", unit: "SGD", weight: 25 }),
      preferred({ id: "oven-prefer-temperature", criterionKey: "max_temperature_c", label: "Prefer a higher maximum temperature", unit: "°C", weight: 25 }),
      preferred({ id: "oven-prefer-volume", criterionKey: "chamber_volume_l", label: "Prefer greater chamber volume", unit: "L", weight: 20 }),
      preferred({ id: "oven-prefer-uniformity", criterionKey: "temperature_uniformity_c", label: "Prefer tighter temperature uniformity", unit: "±°C", weight: 20 }),
      preferred({ id: "oven-prefer-power", criterionKey: "power_consumption_w", label: "Prefer lower power consumption", unit: "W", weight: 10 }),
    ],
  },
];

export const categoryConfigs = categoryConfigSchema.array().length(3).parse(rawCategoryConfigs);

export const categoryConfigById = Object.fromEntries(
  categoryConfigs.map((config) => [config.category, config]),
) as Record<CategoryConfig["category"], CategoryConfig>;
